# Generated by Django 4.2.2 on 2023-06-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(default=1, max_length=8, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
