# Generated by Django 4.2.2 on 2023-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_userinfo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
