# Generated by Django 4.2.2 on 2023-06-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_failmail_delete_falimail_replymail_isfinish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failmail',
            old_name='isFinish',
            new_name='isOpen',
        ),
        migrations.RenameField(
            model_name='replymail',
            old_name='isFinish',
            new_name='isOpen',
        ),
        migrations.RenameField(
            model_name='successmail',
            old_name='isFinish',
            new_name='isOpen',
        ),
    ]
