# Generated by Django 4.2.2 on 2023-06-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0006_rename_isfinish_failmail_isopen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='uid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='url',
            field=models.CharField(default=1, max_length=999, verbose_name='头像URL'),
            preserve_default=False,
        ),
    ]
