# Generated by Django 4.2.2 on 2023-06-30 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0007_remove_userinfo_uid_userinfo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failmail',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='replymail',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='successmail',
            name='uid',
        ),
        migrations.AddField(
            model_name='failmail',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replymail',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successmail',
            name='phone',
            field=models.CharField(default=1, max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='failCount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='失败条数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='replyCount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='回复条数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='successCount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='成功条数'),
        ),
    ]
