# Generated by Django 4.2.2 on 2023-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0009_userinfo_openid_userinfo_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='failmail',
            name='forPhone',
            field=models.CharField(default=1, max_length=11, verbose_name='对方手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replymail',
            name='forPhone',
            field=models.CharField(default=1, max_length=11, verbose_name='对方手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successmail',
            name='forPhone',
            field=models.CharField(default=1, max_length=11, verbose_name='对方手机号'),
            preserve_default=False,
        ),
    ]
