# Generated by Django 4.2.2 on 2023-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0010_failmail_forphone_replymail_forphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failmail',
            name='uid',
            field=models.CharField(default=1, max_length=11, verbose_name='uid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replymail',
            name='uid',
            field=models.CharField(default=1, max_length=11, verbose_name='uid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successmail',
            name='uid',
            field=models.CharField(default=1, max_length=11, verbose_name='uid'),
            preserve_default=False,
        ),
    ]
