# Generated by Django 4.2.2 on 2023-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0011_failmail_uid_replymail_uid_successmail_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failmail',
            name='isOpen',
            field=models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=2, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='replymail',
            name='isOpen',
            field=models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=2, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='successmail',
            name='isOpen',
            field=models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=2, verbose_name='是否公开'),
        ),
    ]
