# Generated by Django 4.2.2 on 2023-07-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0012_alter_failmail_isopen_alter_replymail_isopen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failmail',
            name='isOpen',
            field=models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=0, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='replymail',
            name='isOpen',
            field=models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=0, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='successmail',
            name='isOpen',
            field=models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=0, verbose_name='是否公开'),
        ),
    ]
