# Generated by Django 4.2.2 on 2023-07-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0013_alter_failmail_isopen_alter_replymail_isopen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failmail',
            old_name='fail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='replymail',
            old_name='reply',
            new_name='mail',
        ),
    ]
