# Generated by Django 4.2.2 on 2023-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0014_rename_fail_failmail_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failmail',
            name='sendTime',
            field=models.CharField(default=1, max_length=20, verbose_name='发送时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replymail',
            name='sendTime',
            field=models.CharField(default=1, max_length=20, verbose_name='发送时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successmail',
            name='sendTime',
            field=models.CharField(default=1, max_length=20, verbose_name='发送时间'),
            preserve_default=False,
        ),
    ]
