# Generated by Django 4.2.2 on 2023-07-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0015_failmail_sendtime_replymail_sendtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failmail',
            name='nickName',
            field=models.CharField(default=1, max_length=8, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replymail',
            name='nickName',
            field=models.CharField(default=1, max_length=8, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successmail',
            name='nickName',
            field=models.CharField(default=1, max_length=8, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
