# Generated by Django 4.2.2 on 2023-07-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0016_failmail_nickname_replymail_nickname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failmail',
            options={'ordering': ['-sendTime']},
        ),
        migrations.AlterModelOptions(
            name='replymail',
            options={'ordering': ['-sendTime']},
        ),
        migrations.AlterModelOptions(
            name='successmail',
            options={'ordering': ['-sendTime']},
        ),
    ]
