# Generated by Django 4.2.2 on 2023-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0017_alter_failmail_options_alter_replymail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='successmail',
            name='imgUrl',
            field=models.CharField(default=1, max_length=999, verbose_name='头像地址'),
            preserve_default=False,
        ),
    ]
