# Generated by Django 4.2.2 on 2023-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0018_successmail_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11, verbose_name='uid')),
                ('way', models.SmallIntegerField(choices=[(1, '微信'), (2, 'QQ'), (3, '抖音'), (4, '快手'), (5, '微博'), (6, '小红书')], default=1, verbose_name='联系方式')),
                ('phone', models.CharField(max_length=11, verbose_name='用户手机号')),
                ('forPhone', models.CharField(max_length=11, verbose_name='对方手机号')),
                ('isOpen', models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=0, verbose_name='是否公开')),
                ('sendTime', models.CharField(max_length=20, verbose_name='发送时间')),
                ('nickName', models.CharField(max_length=8, verbose_name='昵称')),
            ],
        ),
        migrations.AlterField(
            model_name='successmail',
            name='uid',
            field=models.CharField(max_length=11, verbose_name='订单号'),
        ),
    ]
