# Generated by Django 4.2.2 on 2023-07-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0019_labour_alter_successmail_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='mail',
            field=models.CharField(default=1, max_length=9999, verbose_name='短信内容'),
            preserve_default=False,
        ),
    ]
