# Generated by Django 4.2.2 on 2023-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0020_labour_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='way',
            field=models.SmallIntegerField(choices=[(0, '微信'), (1, 'QQ'), (2, '抖音'), (3, '快手'), (4, '微博'), (5, '小红书')], default=0, verbose_name='联系方式'),
        ),
    ]
