# Generated by Django 4.2.2 on 2023-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0021_alter_labour_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='way',
            field=models.SmallIntegerField(choices=[(1, '微信'), (2, 'QQ'), (3, '抖音'), (4, '快手'), (5, '微博'), (6, '小红书')], default=0, verbose_name='联系方式'),
        ),
    ]
