# Generated by Django 4.2.2 on 2023-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0022_alter_labour_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='imgUrl',
            field=models.CharField(default=1, max_length=999, verbose_name='头像地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labour',
            name='forPhone',
            field=models.CharField(max_length=11, verbose_name='对方账号'),
        ),
    ]
