# Generated by Django 4.2.2 on 2023-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0023_labour_imgurl_alter_labour_forphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='isSend',
            field=models.SmallIntegerField(choices=[(1, 'true'), (0, 'false')], default=0, verbose_name='是否发送'),
        ),
    ]
