# Generated by Django 4.2.2 on 2023-07-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0024_labour_issend'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forName', models.CharField(max_length=99, verbose_name='对方名称')),
                ('nickName', models.CharField(default='匿名用户', max_length=8, verbose_name='昵称')),
                ('imgUrl', models.CharField(default='https://mp-891a44a8-f007-4426-a7a4-607ad2bc43d0.cdn.bspapp.com/email/0.png', max_length=999, verbose_name='头像地址')),
                ('sendTime', models.CharField(max_length=20, verbose_name='发送时间')),
                ('mail', models.CharField(max_length=800, verbose_name='留言')),
            ],
        ),
    ]
