# Generated by Django 4.2.2 on 2023-07-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0026_leaves_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='uid',
            field=models.CharField(default=1, max_length=11, verbose_name='订单号'),
            preserve_default=False,
        ),
    ]
