# Generated by Django 4.2.3 on 2023-07-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0027_leaves_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replymail',
            options={},
        ),
        migrations.RemoveField(
            model_name='replymail',
            name='isOpen',
        ),
        migrations.RemoveField(
            model_name='replymail',
            name='nickName',
        ),
        migrations.AddField(
            model_name='replymail',
            name='myMail',
            field=models.CharField(default=1, max_length=800, verbose_name='我的短信'),
            preserve_default=False,
        ),
    ]
